// Code generated by gen-fields; DO NOT EDIT.

package transmission

// SessionField is a field of Session
type SessionField string

const (
	SessionFieldID                         SessionField = "session-id"
	SessionFieldTurtleDownloadRateLimit    SessionField = "alt-speed-down"
	SessionFieldTurtleUploadRateLimit      SessionField = "alt-speed-up"
	SessionFieldTurtleEnabled              SessionField = "alt-speed-enabled"
	SessionFieldTurtleScheduleEnabled      SessionField = "alt-speed-time-enabled"
	SessionFieldTurtleScheduleOnDays       SessionField = "alt-speed-time-day"
	SessionFieldTurtleScheduleStartsAt     SessionField = "alt-speed-time-begin"
	SessionFieldTurtleScheduleStopsAt      SessionField = "alt-speed-time-end"
	SessionFieldDownloadRateLimit          SessionField = "speed-limit-down"
	SessionFieldDownloadRateLimitEnabled   SessionField = "speed-limit-down-enabled"
	SessionFieldUploadRateLimit            SessionField = "speed-limit-up"
	SessionFieldUploadRateLimitEnabled     SessionField = "speed-limit-up-enabled"
	SessionFieldBlocklistURL               SessionField = "blocklist-url"
	SessionFieldBlocklistEnabled           SessionField = "blocklist-enabled"
	SessionFieldBlocklistSize              SessionField = "blocklist-size"
	SessionFieldCacheSize                  SessionField = "cache-size-mb"
	SessionFieldConfigDirectory            SessionField = "config-dir"
	SessionFieldDownloadDirectory          SessionField = "download-dir"
	SessionFieldIncompleteDirectory        SessionField = "incomplete-dir"
	SessionFieldIncompleteDirectoryEnabled SessionField = "incomplete-dir-enabled"
	SessionFieldRenameIncompleteFiles      SessionField = "rename-partial-files"
	SessionFieldDownloadQueueLimit         SessionField = "download-queue-size"
	SessionFieldDownloadQueueLimitEnabled  SessionField = "download-queue-enabled"
	SessionFieldUploadQueueLimit           SessionField = "seed-queue-size"
	SessionFieldUploadQueueLimitEnabled    SessionField = "seed-queue-enabled"
	SessionFieldQueueStalled               SessionField = "queue-stalled-minutes"
	SessionFieldQueueStalledEnabled        SessionField = "queue-stalled-enabled"
	SessionFieldUploadRatio                SessionField = "seedRatioLimit"
	SessionFieldUploadRatioEnabled         SessionField = "seedRatioLimited"
	SessionFieldDHTEnabled                 SessionField = "dht-enabled"
	SessionFieldLPDEnabled                 SessionField = "lpd-enabled"
	SessionFieldPEXEnabled                 SessionField = "pex-enabled"
	SessionFieldUTPEnabled                 SessionField = "utp-enabled"
	SessionFieldEncryption                 SessionField = "encryption"
	SessionFieldIdleSeedingLimit           SessionField = "idle-seeding-limit"
	SessionFieldIdleSeedingLimitEnabled    SessionField = "idle-seeding-limit-enabled"
	SessionFieldGlobalPeerLimit            SessionField = "peer-limit-global"
	SessionFieldTorrentPeerLimit           SessionField = "peer-limit-per-torrent"
	SessionFieldPeerPort                   SessionField = "peer-port"
	SessionFieldRandomizePeerPort          SessionField = "peer-port-random-on-start"
	SessionFieldPortForwardingEnabled      SessionField = "port-forwarding-enabled"
	SessionFieldScriptPath                 SessionField = "script-torrent-done-filename"
	SessionFieldScriptEnabled              SessionField = "script-torrent-done-enabled"
	SessionFieldAutostartTorrents          SessionField = "start-added-torrents"
	SessionFieldRemoveTorrentFiles         SessionField = "trash-original-torrent-files"
	SessionFieldRPCVersion                 SessionField = "rpc-version"
	SessionFieldRPCVersionMinimum          SessionField = "rpc-version-minimum"
	SessionFieldVersion                    SessionField = "version"
	SessionFieldUnits                      SessionField = "units"
)

var allSessionFields = []SessionField{
	SessionFieldID,
	SessionFieldTurtleDownloadRateLimit,
	SessionFieldTurtleUploadRateLimit,
	SessionFieldTurtleEnabled,
	SessionFieldTurtleScheduleEnabled,
	SessionFieldTurtleScheduleOnDays,
	SessionFieldTurtleScheduleStartsAt,
	SessionFieldTurtleScheduleStopsAt,
	SessionFieldDownloadRateLimit,
	SessionFieldDownloadRateLimitEnabled,
	SessionFieldUploadRateLimit,
	SessionFieldUploadRateLimitEnabled,
	SessionFieldBlocklistURL,
	SessionFieldBlocklistEnabled,
	SessionFieldBlocklistSize,
	SessionFieldCacheSize,
	SessionFieldConfigDirectory,
	SessionFieldDownloadDirectory,
	SessionFieldIncompleteDirectory,
	SessionFieldIncompleteDirectoryEnabled,
	SessionFieldRenameIncompleteFiles,
	SessionFieldDownloadQueueLimit,
	SessionFieldDownloadQueueLimitEnabled,
	SessionFieldUploadQueueLimit,
	SessionFieldUploadQueueLimitEnabled,
	SessionFieldQueueStalled,
	SessionFieldQueueStalledEnabled,
	SessionFieldUploadRatio,
	SessionFieldUploadRatioEnabled,
	SessionFieldDHTEnabled,
	SessionFieldLPDEnabled,
	SessionFieldPEXEnabled,
	SessionFieldUTPEnabled,
	SessionFieldEncryption,
	SessionFieldIdleSeedingLimit,
	SessionFieldIdleSeedingLimitEnabled,
	SessionFieldGlobalPeerLimit,
	SessionFieldTorrentPeerLimit,
	SessionFieldPeerPort,
	SessionFieldRandomizePeerPort,
	SessionFieldPortForwardingEnabled,
	SessionFieldScriptPath,
	SessionFieldScriptEnabled,
	SessionFieldAutostartTorrents,
	SessionFieldRemoveTorrentFiles,
	SessionFieldRPCVersion,
	SessionFieldRPCVersionMinimum,
	SessionFieldVersion,
	SessionFieldUnits,
}
