name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Install cachix
        uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest
      - name: Setup nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Setup go cache
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run pre-commit hooks
        run: |
          devenv shell pre-commit run --all-files
      - name: Ensure generated files are up-to-date
        run: |
          devenv shell go generate ./... && git diff --exit-code
