name: CI
on: [push]

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-contrib/golangci-lint@v1

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - run: go test -race -cover ./...

# vim: set ts=2 sw=2 expandtab:
